name: bitmec
description: Bitmec application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_inappwebview: ^2.1.0+1
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  provider: ^4.0.1
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  image_picker: ^0.6.3+1
  dio: ^3.0.8
  path: ^1.6.4
  agora_rtc_engine: ^1.0.8
  permission_handler: ^4.4.0+hotfix.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  random_color: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
